### ISSUE TITLE
Use as a Global allocator with malloc/free as a backend

### ISSUE THREAD

**Issue by VariantXYZ** [zakarumych/blink-alloc#2]
I think this allocator would be really useful as the default Rust allocator when generating C-compatible libraries.

It seems feasible to allow for configuring a backend as part of the allocator generic parameter (e.g just providing aligned_alloc and free or a wrapped GlobalAlloc implementation to line-up with new_in). Alternatively, just defaulting to using System as the backend.

What do you think?

**Comment by zakarumych** [comment]
It would be a bit unsafe to use as a global allocator.
The reset requires mutable borrow for this reason.

However I already plan to add 'fn reset_unchecked(&self)' exactly for usage with static instance.

With this in place and GlobalAlloc implementation for BlinkAlloc<A> it can be set as default allocator.
Where A should not be anything not Global baked.
Maybe requiring A: Allocator + GlobalAlloc would work.

**Comment by VariantXYZ** [comment]
> With this in place and GlobalAlloc implementation for BlinkAlloc it can be set as default allocator.

It would need to implement Sync, wouldn't it?

> Maybe requiring A: Allocator + GlobalAlloc would work.
Being able to rely on 'System' would be nice, which I believe would satisfy these bounds and make a really intuitive default.

**Comment by zakarumych** [comment]
For `global_allocator` `System` is a nice default.
For general `Allocator` `Global` seems better default.
And `System` is available only with `std`.
It would probably make sense to make a wrapper type that implements `GlobalAlloc` and has `System` as default when `"std"` is enabled and no default otherwise. Similarly to `Global` being default only if `"alloc"` is enabled.

**Comment by zakarumych** [comment]
It is also possible to create more interesting scheme, where `struct GlobalBlinkAlloc;` is a ZST that acts as `global_allocator`
and uses `thread_local` instances of `LocalBlinkAlloc` that share static `SyncBlinkAlloc`.

**Comment by zakarumych** [comment]
Resetting the shared `SyncBlinkAlloc` would be highly unsafe, but for thread-local instances of `LocalBlinkAlloc` it would be easier to ensure safety.

**Comment by VariantXYZ** [comment]
Ah, though it's a bit odd, my use-case actually explicitly is trying to avoid TLS due to performance concerns... Though, this allocator's implementation may help with that (the biggest issue is accessing TLS constantly, even if I only have one active thread).

> Instead of BlinkAlloc the SyncBlinkAlloc can be used for global_allocator. It is Sync already.

This would be useful to have.

**Comment by zakarumych** [comment]
When uncondended `SyncBlinkAlloc` is few times slower than `BlinkAlloc` due to 3 atomic ops for allocation.
If you KNOW that you got only one thread that may access `BlinkAlloc` it can be made into `global_allocator` with unsafe call I guess.

**Comment by VariantXYZ** [comment]
I guess... something like this? Though I think my casting is a little shady.

```
use allocator_api2::alloc::{GlobalAlloc, Layout, System};
use core::ptr::NonNull;

static mut BLINK: blink_alloc::BlinkAlloc<System> = blink_alloc::BlinkAlloc::new_in(System);

struct Allocator;

unsafe impl GlobalAlloc for Allocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        BLINK.allocate(layout).unwrap().cast::<u8>().as_ptr()
        //System.alloc(layout)
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        BLINK.deallocate(NonNull::new_unchecked(ptr), layout.size());
        //System.dealloc(ptr, layout)
    }
}
pub unsafe fn alloc_reset() {
    BLINK.reset();
}

#[global_allocator]
static GLOBAL: Allocator = Allocator;
```

**Comment by VariantXYZ** [comment]
Regarding the issue I was running into:

> It's because the "state" I am initializing can change as part of the processing. As a result, when something in that state object is allocated during processing, it will use the blink allocator and the state will get affected by the reset call.

I suppose it's probably obvious, but I've worked around it a bit. I figure it may be worth noting in your documentation as this seems like a fairly common situation people would run into. Things seem to be working great though, appreciate this feature!
```
fn init() {
    unsafe { BLINK.direct_mode(); }
    
    // Allocate permanent state object
   
}
```
```
fn repeated_function(state: mut c_void*) {
    unsafe { BLINK.blink_mode(); }
    blink_state = state.clone(); // 'state' is in direct memory, 'blink_state' is in blink memory

    // Do useful stuff

    unsafe { BLINK.direct_mode(); }
    state = blink_state.clone(); // Update state
    unsafe { BLINK.blink_mode(); }

    BLINK.reset(); // Clear repeated memory
}
```

**Comment by zakarumych** [comment]
Thank you for suggestion. I will add this into `# Examples` section for the type.
