### ISSUE TITLE
`impl Allocator for &BlinkAlloc<A>`?

### ISSUE THREAD

**Issue by nical** [zakarumych/blink-alloc#4]
Hi,

I see that BlinkAlloc implements Allocator for itself and as a &mut reference. Would it be possible to add an implementation for `&BlinkAlloc` as well? Restricting to &mut references means only one data structure can use the allocator at a time, maybe that's intentional?

**Comment by nical** [comment]
Apologies, it appears to work. I didn't find the impl in the [doc](https://docs.rs/blink-alloc/latest/blink_alloc/struct.BlinkAlloc.html#impl-Allocator-for-%26mut+BlinkAlloc%3CA%3E) but passing a `&BlinkAlloc` to couple of containers actually works.

**Comment by zakarumych** [comment]
This works because of blanket impl in `core`. `impl<A> Allocator for &A where A: Allocator {}`
